## Optional Docker-Compose which starts up a notebook environment and pipeline environment
version: "3.7"
services:
    competition_notebook:
        container_name: "competition_notebook"
        image: "competition_notebook:latest"
        tty: true
        build: 
            context: .
        ports: 
            - "8888:8888"
        volumes: 
            - .:/app
        command: jupyter-lab --no-browser --port=8888 --ip=0.0.0.0 --allow-root
    competition_pipeline:
        container_name: "competition_pipeline"
        image: "competition_pipeline:latest"
        tty: true
        build: 
            context: .
        runtime: nvidia
        environment:
        - NVIDIA_VISIBLE_DEVICES=all
        volumes: 
            - .:/app
        command: nvidia-smi -l 1